version: "3"

services:
    sae_int:
      build:
        context: .
        dockerfile: Dockerfile
      image: sae_int
      container_name: sae_int
      restart: always
      env_file:
        - .env
      ports:
        - "0.0.0.0:3037:3037"
        - "0.0.0.0:3036:3036"
      networks:
        nodes-networks:
          aliases:
            - sae_int

networks:
  nodes-networks:
    external: true